apiVersion: v2
name: netobserv
description: ElastiFlow NetObserv
type: application
version: 0.0.16
appVersion: 6.4.3

keywords:
  - netflow
  - network
  - flow
  - observability

sources:
  - https://github.com/elastiflow/helm-chart-netobserv
  - https://hub.docker.com/r/elastiflow/flowcollector/
maintainers:
  - name: ElastiFlow Engineering Team
    email: engineering@elastiflow.com

dependencies:
  # https://github.com/elastic/cloud-on-k8s
  - name: eck-operator
    repository: https://helm.elastic.co
    version: "2.12.*"
    condition: elasticsearch.enabled
  # https://opensearch.org/docs/latest/install-and-configure/install-opensearch/helm/
  - name: opensearch
    repository: https://opensearch-project.github.io/helm-charts/
    version: "2.20.*"
    condition: opensearch.enabled
